openapi: 3.0.3
info:
  title: Mortgage User Authentication Contract
  version: "1.0.0"
servers:
  - url: /

paths:
  /user/register:
    post:
      summary: Register new user
      operationId: registerUser
      requestBody:
        description: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      responses:
        '200':
          description: 'Response '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        400:
          description: 'Response '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: 'Response '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/login:
    post:
      summary: Login with email and password
      operationId: login
      requestBody:
        description: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
        required: true
      responses:
        '200':
          description: 'Response '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        400:
          description: 'Response '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: 'Response '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string

    AuthenticationRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string


    AuthenticationResponse:
      type: object
      properties:
        authToken:
          type: string

    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
